config/routes.rb
Rails.application.routes.draw do
  resources :places #except: [:index, :show]
  delete 'places/:id', to:"places#destroy", as: 'delete_place'
  resources :sessions
  resources :users

end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :longitute, presence: true
	validates :longitute, uniqueness: true
	validates :latitude, presence: true
	validates :latitude, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	#callback
	before_create :set_auth_token
	has_secure_password

	validates :email, presence: true, uniqueness: true
	#namabhin validasi untuk keberadaan password dan password konfirmasi
	def set_auth_token
		#looping dan generate number
		#break dari loop kalo ketemu number yang belum kepake
		self.auth_token = loop do
			token = SecureRandom.hex
			break token if !self.class.exists?(auth_token: token)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    logger.debug params
    @current_user = if params[:token]
      #user based on token
      User.find_by(auth_token: params[:token])
    else
      User.find(session[:user_id]) if session[:user_id]
    end
  end

  def authorize
    respond_to do |format|
  	format.html {redirect_to new_session_path, alert: "Unauthorized Accesss" if !current_user}
    format.json {render json: "Unauthorized Accesss" if !current_user}
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authorize, except: [:index, :show]
	def new
		@place = Place.new
	end

	def show
		place = Place.find(params[:id])
		render json: post
	end

  	def update
  		#minta objeknya ke model
  		@place = Place.find(params[:id])
  		@place.update(params.require(:place).
  			permit(:name, :longitute, :latitude))
  		redirect_to new_place_path, notice: "Succesfully update the post!"
	end

	def index
		@places = Place.all
		respond_to do |format|
			format.html
			format.json {render json: @places}
			format.xml {render xml: @places}
		end
	end

	def destroy
		place = Place.find(params[:id])
		place.destroy
		redirect_to places_path
	end

	def create
		#render json:params
		@place = Place.new(params.require(:place)
			.permit(:name, :longitute, :latitude))
		respond_to do |format|
			if @place.save
				format.html {redirect_to places_path, notice: "Succesfully save the place"}
				format.json {render json:@place}
			else
				format.html {render :new}
				format.json {render json:@place.errors}
			end
		end
	end

	def edit
		@place = Place.find(params[:id])
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		respond_to do |format|
			if user && user.authenticate(params[:password])
				#loginsuccesfull
			 	format.html do
					session[:user_id] = user.id
					redirect_to places_path, notice: "Logged In!"
				end
				format.json {render json: user}
			else
				format.html do
					flash.now.alert = "Invalid email or password"
					render :new
				end
				format.json {render json: "Invalid email or password"}
			end
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to places_path, notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params.require(:user)
			.permit(:email, :password, :password_confirmation))

		respond_to do |format|
		if @user.save
			#@user.update(auth_token: "kkkk")
			session[:user_id] = @user.id
			format.html {redirect_to new_user_path, notice: "Succesfully"}
			format.json {render json: @user}
			#redirect_to new_user_path
		else
			format.html {render :new}
			format.json {render json:@user.errors}
			#render :new
		end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Peta', places_path %> </h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Hello, <%=current_user ? current_user.email : 'Guest' %></a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <% if current_user %>
        <li><%= link_to "Log Out", session_path(current_user), method: 'delete' %> </li>
      <% else %>
      <li><%= link_to "Log In", new_session_path %> </li>
      <li><%= link_to "Sign Up", new_user_path %> </li>
      <% end %> 
    </ul>
  </section>
</nav>
<% if notice %>
  <div data-alert class="alert-box alert radius">
  T<%= notice %>
  <a href="#" class="close">&times;</a>
</div>
  <% end %>
  <% if alert %>
  <div data-alert class="alert-box success radius">
  <%= alert %>
  <a href="#" class="close">&times;</a>
</div>
<% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/places/edit.html.erb
<h1> Edit Place </h1>
<% if !@place.errors.empty? %>
	<% @place.errors.full_messages.each do |msg| %>
		<h4 style="color:red;"><%= msg %></h4>
		<% end %> 
	<% end %>
<%= form_for @place do |f| %>
	<%= f.label :name %> :
	<%= f.text_field :name %>
	<br/>
	<%= f.label :longitute %> : 
	<%= f.text_field :longitute %>
	</br>
	<%= f.label :latitude %> : 
	<%= f.text_field :latitude %>
	<br/>
<%= f.submit %>
<% end %>

app/views/places/index.html.erb
<h1> All Place </h1>
	<table>
		<tr>
			<th>Name</th>
			<th>Longitute</th>
			<th>Latitude</th>
</tr>
<tr>	
<% @places.each do |place| %>
	<tr>
		<td><%=place.name %></td>
		<td><%=place.longitute %></td>
		<td><%=place.latitude %></td>
		<td><%= link_to 'Edit', edit_place_path(place) %></td>
		<td><%= link_to 'Delete',
			delete_place_path(place), method: 'delete' %> </td>
	</tr>
	<% end %>
</table>
<br>
<br>
<%= link_to 'New Post' , new_place_path %> 

app/views/places/new.html.erb
<h1> New Place </h1>
<% if !@place.errors.empty? %>
	<% @place.errors.full_messages.each do |msg| %>
		<h4 style="color:red;"><%= msg %></h4>
		<% end %> 
	<% end %>
<%= form_for @place do |f| %>
	<%= f.label :name %> :
	<%= f.text_field :name %>
	<br/>
	<%= f.label :longitute %> : 
	<%= f.text_field :longitute %>
	</br>
	<%= f.label :latitude %> : 
	<%= f.text_field :latitude %>
	<br/>
<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>
<% if !@user.errors.empty? %>
	<% @user.errors.full_messages.each do |msg| %>
		<h4 style="color:red;"><%= msg %></h4>
		<% end %> 
	<% end %>
<%= form_for @user do |f| %>
	<%= f.label :email %> :
	<%= f.text_field :email %>
	<br/>
	<%= f.label :password %> : 
	<%= f.password_field :password %>
	</br>
	<%= f.label :password_confirmation %> : 
	<%= f.password_field :password_confirmation %>
	<br/>
<%= f.submit %>
<% end %>